### PR TITLE
fix: lock requests version to 2.29.0

### PR DESCRIPTION
**Pull request by vvanglro**
Fixes: pdm issue [#2091](https://github.com/pdm-project/pdm/issues/2091)

Related `requests`question link: [#6443](https://github.com/psf/requests/issues/6443)

### CODE REVIEW

**Comment by frostming** [comment]
Sorry, can you describe the details of the issue and your investigation that makes you believe this is the only viable way to fix it? We don't want a solution that "happens to make it work"

**Comment by vvanglro** [comment]
> You mentioned #2091 but that issue is related to cachecontrol which is not included in this project.

What does mean in relation to cache control? I saw that the error message was sent from the unearth library. https://github.com/pdm-project/pdm/issues/2091#issue-1792585284

**Comment by vvanglro** [comment]
> Sorry, can you describe the details of the issue and your investigation that makes you believe this is the only viable way to fix it? We don't want a solution that "happens to make it work".

For now, people who encounter the same error are solved by locking requests version 2.29.0. https://github.com/psf/requests/issues/6443#issuecomment-1568210854

**Comment by frostming** [comment]
> For now, people who encounter the same error are solved by locking requests version 2.29.0. [psf/requests#6443 (comment)](https://github.com/psf/requests/issues/6443#issuecomment-1568210854)

I would like to see more investigation of the nature of the bug. "do A and the bug is gone, so the solution is to do A" isn't enough.

**Comment by vvanglro** [comment]
Yes, I agree. Needs more investigation as I couldn't reproduce either. Maybe something to do with the network used locally.

**Pull request closed without merging**
